language: php

php:
  - 7.2

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - echo "test"
  # - ./vendor/bin/phpunit --verbose

cache:
  directories:
    - vendor

branches:
  only:
    - master